# Site settings
title: Samara F. Kiihl
email: samara@ime.unicamp.br
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  samarafk
googlescholar_username: BfRFGWsAAAAJ

# Build settings
markdown: kramdown
